In [1]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv(r'outputs/initial_soc_charging_sensitivity/combined_summary.csv')
data

,configured_initial_battery_mean,realized_initial_battery_mean,realized_initial_battery_mean_human_ev,realized_initial_battery_mean_aev,battery_consumption_ratio,effective_consumption_wh_per_mile,effective_consumption_kwh_per_km,num_seeds,avg_daily_charging_sessions_per_human_ev,std_avg_daily_charging_sessions_per_human_ev,...,std_mcmf_aev_relocate_selections,mcmf_low_soc_aev_charge_selections,std_mcmf_low_soc_aev_charge_selections,mcmf_low_soc_aev_wait_selections,std_mcmf_low_soc_aev_wait_selections,pct_change_vs_baseline_avg_daily_charging_sessions_per_human_ev,pct_change_vs_baseline_avg_daily_charging_sessions_per_aev,pct_change_vs_baseline_avg_daily_charging_sessions_per_vehicle,pct_change_vs_baseline_avg_wait_minutes_waiting_charging_vehicles,initial_soc_case
0,0.875,0.873609,0.873309,0.873909,0.8000,184.000,0.114332,3,5.716667,0.118977,...,194.074442,0.000000,0.000000,0.000000,0.000000,0.704639,0.000000,0.704639,-19.840113,0.875
1,0.875,0.873609,0.873309,0.873909,0.9025,207.575,0.128981,3,5.470000,0.168721,...,126.965437,0.000000,0.000000,0.000000,0.000000,-3.640634,0.000000,-3.640634,-2.985102,0.875
2,0.875,0.873609,0.873309,0.873909,0.9500,218.500,0.135770,3,5.626667,0.161314,...,184.934223,0.000000,0.000000,0.000000,0.000000,-0.880799,0.000000,-0.880799,14.901722,0.875
3,0.875,0.873609,0.873309,0.873909,1.0000,230.000,0.142915,3,5.676667,0.254864,...,169.304459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.875
4,0.875,0.873609,0.873309,0.873909,1.0500,241.500,0.150061,3,5.780000,0.131403,...,156.552441,0.000000,0.000000,0.000000,0.000000,1.820317,0.000000,1.820317,9.123869,0.875
5,0.875,0.873609,0.873309,0.873909,1.1025,253.575,0.157564,3,5.913333,0.122565,...,279.457013,0.000000,0.000000,0.000000,0.000000,4.169113,0.000000,4.169113,17.896236,0.875
6,0.875,0.873609,0.873309,0.873909,1.2000,276.000,0.171498,3,5.820000,0.101980,...,256.916329,0.000000,0.000000,0.000000,0.000000,2.524956,0.000000,2.524956,54.190675,0.875
7,0.450,0.448609,0.448309,0.448909,0.8000,184.000,0.114332,3,5.740000,0.160624,...,180.694955,0.000000,0.000000,0.000000,0.000000,1.953819,0.000000,1.953819,4.790875,0.450
8,0.450,0.448609,0.448309,0.448909,0.9025,207.575,0.128981,3,5.786667,0.020548,...,232.926789,0.000000,0.000000,0.000000,0.000000,2.782712,0.000000,2.782712,0.435395,0.450
9,0.450,0.448609,0.448309,0.448909,0.9500,218.500,0.135770,3,5.450000,0.347083,...,280.725647,0.000000,0.000000,0.000000,0.000000,-3.197158,0.000000,-3.197158,5.802952,0.450
10,0.450,0.448609,0.448309,0.448909,1.0000,230.000,0.142915,3,5.630000,0.090921,...,132.751229,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450
11,0.450,0.448609,0.448309,0.448909,1.0500,241.500,0.150061,3,5.630000,0.151217,...,170.513603,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.405275,0.450
12,0.450,0.448609,0.448309,0.448909,1.1025,253.575,0.157564,3,5.666667,0.298478,...,207.454948,0.000000,0.000000,0.000000,0.000000,0.651273,0.000000,0.651273,7.293101,0.450
13,0.450,0.448609,0.448309,0.448909,1.2000,276.000,0.171498,3,5.573333,0.084984,...,43.606829,0.000000,0.000000,0.000000,0.000000,-1.006513,0.000000,-1.006513,11.544812,0.450
14,0.150,0.148609,0.148309,0.148909,0.8000,184.000,0.114332,3,1.113333,0.174420,...,1895.275764,69.000000,7.483315,21704.333333,1855.580652,-1.474926,1.980198,-0.184843,10.953632,0.150
15,0.150,0.148609,0.148309,0.148909,0.9025,207.575,0.128981,3,1.083333,0.097411,...,2016.366204,67.333333,7.845735,21877.000000,1690.174744,-4.129794,-0.495050,-2.772643,16.490256,0.150
16,0.150,0.148609,0.148309,0.148909,0.9500,218.500,0.135770,3,0.990000,0.214165,...,1655.478984,68.000000,7.483315,21619.000000,2295.585474,-12.389381,0.990099,-7.393715,16.748224,0.150
17,0.150,0.148609,0.148309,0.148909,1.0000,230.000,0.142915,3,1.130000,0.189912,...,1676.048196,67.666667,6.599663,21115.666667,2207.095427,0.000000,0.000000,0.000000,0.000000,0.150
18,0.150,0.148609,0.148309,0.148909,1.0500,241.500,0.150061,3,1.013333,0.103387,...,1483.369213,68.000000,8.041559,21694.333333,2282.710426,-10.324484,-0.495050,-6.654344,15.305230,0.150
19,0.150,0.148609,0.148309,0.148909,1.1025,253.575,0.157564,3,1.096667,0.069442,...,1460.571197,67.333333,8.178563,21751.333333,2303.804727,-2.949853,-0.495050,-2.033272,17.792232,0.150
20,0.150,0.148609,0.148309,0.148909,1.2000,276.000,0.171498,3,0.990000,0.162686,...,1311.971629,68.666667,7.408704,21576.333333,2226.397589,-12.389381,1.485149,-7.208872,10.768495,0.150

In [ ]:
data = pd.read_csv(r'outputs/initial_soc_charging_sensitivity/combined_summary.csv')
label_map = {
     0.875: 'H',
    0.450: "M",
    0.150:"L"
}
data['configured_initial_battery_mean'] = data['configured_initial_battery_mean'].map(label_map)
columns = ['configured_initial_battery_mean', ]

,configured_initial_battery_mean,realized_initial_battery_mean,realized_initial_battery_mean_human_ev,realized_initial_battery_mean_aev,battery_consumption_ratio,effective_consumption_wh_per_mile,effective_consumption_kwh_per_km,num_seeds,avg_daily_charging_sessions_per_human_ev,std_avg_daily_charging_sessions_per_human_ev,...,std_mcmf_aev_relocate_selections,mcmf_low_soc_aev_charge_selections,std_mcmf_low_soc_aev_charge_selections,mcmf_low_soc_aev_wait_selections,std_mcmf_low_soc_aev_wait_selections,pct_change_vs_baseline_avg_daily_charging_sessions_per_human_ev,pct_change_vs_baseline_avg_daily_charging_sessions_per_aev,pct_change_vs_baseline_avg_daily_charging_sessions_per_vehicle,pct_change_vs_baseline_avg_wait_minutes_waiting_charging_vehicles,initial_soc_case
0,H,0.873609,0.873309,0.873909,0.8000,184.000,0.114332,3,5.716667,0.118977,...,194.074442,0.000000,0.000000,0.000000,0.000000,0.704639,0.000000,0.704639,-19.840113,0.875
1,H,0.873609,0.873309,0.873909,0.9025,207.575,0.128981,3,5.470000,0.168721,...,126.965437,0.000000,0.000000,0.000000,0.000000,-3.640634,0.000000,-3.640634,-2.985102,0.875
2,H,0.873609,0.873309,0.873909,0.9500,218.500,0.135770,3,5.626667,0.161314,...,184.934223,0.000000,0.000000,0.000000,0.000000,-0.880799,0.000000,-0.880799,14.901722,0.875
3,H,0.873609,0.873309,0.873909,1.0000,230.000,0.142915,3,5.676667,0.254864,...,169.304459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.875
4,H,0.873609,0.873309,0.873909,1.0500,241.500,0.150061,3,5.780000,0.131403,...,156.552441,0.000000,0.000000,0.000000,0.000000,1.820317,0.000000,1.820317,9.123869,0.875
5,H,0.873609,0.873309,0.873909,1.1025,253.575,0.157564,3,5.913333,0.122565,...,279.457013,0.000000,0.000000,0.000000,0.000000,4.169113,0.000000,4.169113,17.896236,0.875
6,H,0.873609,0.873309,0.873909,1.2000,276.000,0.171498,3,5.820000,0.101980,...,256.916329,0.000000,0.000000,0.000000,0.000000,2.524956,0.000000,2.524956,54.190675,0.875
7,M,0.448609,0.448309,0.448909,0.8000,184.000,0.114332,3,5.740000,0.160624,...,180.694955,0.000000,0.000000,0.000000,0.000000,1.953819,0.000000,1.953819,4.790875,0.450
8,M,0.448609,0.448309,0.448909,0.9025,207.575,0.128981,3,5.786667,0.020548,...,232.926789,0.000000,0.000000,0.000000,0.000000,2.782712,0.000000,2.782712,0.435395,0.450
9,M,0.448609,0.448309,0.448909,0.9500,218.500,0.135770,3,5.450000,0.347083,...,280.725647,0.000000,0.000000,0.000000,0.000000,-3.197158,0.000000,-3.197158,5.802952,0.450
10,M,0.448609,0.448309,0.448909,1.0000,230.000,0.142915,3,5.630000,0.090921,...,132.751229,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450
11,M,0.448609,0.448309,0.448909,1.0500,241.500,0.150061,3,5.630000,0.151217,...,170.513603,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.405275,0.450
12,M,0.448609,0.448309,0.448909,1.1025,253.575,0.157564,3,5.666667,0.298478,...,207.454948,0.000000,0.000000,0.000000,0.000000,0.651273,0.000000,0.651273,7.293101,0.450
13,M,0.448609,0.448309,0.448909,1.2000,276.000,0.171498,3,5.573333,0.084984,...,43.606829,0.000000,0.000000,0.000000,0.000000,-1.006513,0.000000,-1.006513,11.544812,0.450
14,L,0.148609,0.148309,0.148909,0.8000,184.000,0.114332,3,1.113333,0.174420,...,1895.275764,69.000000,7.483315,21704.333333,1855.580652,-1.474926,1.980198,-0.184843,10.953632,0.150
15,L,0.148609,0.148309,0.148909,0.9025,207.575,0.128981,3,1.083333,0.097411,...,2016.366204,67.333333,7.845735,21877.000000,1690.174744,-4.129794,-0.495050,-2.772643,16.490256,0.150
16,L,0.148609,0.148309,0.148909,0.9500,218.500,0.135770,3,0.990000,0.214165,...,1655.478984,68.000000,7.483315,21619.000000,2295.585474,-12.389381,0.990099,-7.393715,16.748224,0.150
17,L,0.148609,0.148309,0.148909,1.0000,230.000,0.142915,3,1.130000,0.189912,...,1676.048196,67.666667,6.599663,21115.666667,2207.095427,0.000000,0.000000,0.000000,0.000000,0.150
18,L,0.148609,0.148309,0.148909,1.0500,241.500,0.150061,3,1.013333,0.103387,...,1483.369213,68.000000,8.041559,21694.333333,2282.710426,-10.324484,-0.495050,-6.654344,15.305230,0.150
19,L,0.148609,0.148309,0.148909,1.1025,253.575,0.157564,3,1.096667,0.069442,...,1460.571197,67.333333,8.178563,21751.333333,2303.804727,-2.949853,-0.495050,-2.033272,17.792232,0.150
20,L,0.148609,0.148309,0.148909,1.2000,276.000,0.171498,3,0.990000,0.162686,...,1311.971629,68.666667,7.408704,21576.333333,2226.397589,-12.389381,1.485149,-7.208872,10.768495,0.150

In [7]:
data['avg_daily_charging_sessions_per_human_ev']

0     5.716667
1     5.470000
2     5.626667
3     5.676667
4     5.780000
5     5.913333
6     5.820000
7     5.740000
8     5.786667
9     5.450000
10    5.630000
11    5.630000
12    5.666667
13    5.573333
14    1.113333
15    1.083333
16    0.990000
17    1.130000
18    1.013333
19    1.096667
20    0.990000
Name: avg_daily_charging_sessions_per_human_ev, dtype: float64

In [9]:
data['avg_daily_charging_sessions_per_aev']

0     0.000000
1     0.000000
2     0.000000
3     0.000000
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.000000
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14    0.686667
15    0.670000
16    0.680000
17    0.673333
18    0.670000
19    0.670000
20    0.683333
Name: avg_daily_charging_sessions_per_aev, dtype: float64

In [10]:
data

,configured_initial_battery_mean,realized_initial_battery_mean,realized_initial_battery_mean_human_ev,realized_initial_battery_mean_aev,battery_consumption_ratio,effective_consumption_wh_per_mile,effective_consumption_kwh_per_km,num_seeds,avg_daily_charging_sessions_per_human_ev,std_avg_daily_charging_sessions_per_human_ev,...,std_mcmf_aev_relocate_selections,mcmf_low_soc_aev_charge_selections,std_mcmf_low_soc_aev_charge_selections,mcmf_low_soc_aev_wait_selections,std_mcmf_low_soc_aev_wait_selections,pct_change_vs_baseline_avg_daily_charging_sessions_per_human_ev,pct_change_vs_baseline_avg_daily_charging_sessions_per_aev,pct_change_vs_baseline_avg_daily_charging_sessions_per_vehicle,pct_change_vs_baseline_avg_wait_minutes_waiting_charging_vehicles,initial_soc_case
0,0.875,0.873609,0.873309,0.873909,0.8000,184.000,0.114332,3,5.716667,0.118977,...,194.074442,0.000000,0.000000,0.000000,0.000000,0.704639,0.000000,0.704639,-19.840113,0.875
1,0.875,0.873609,0.873309,0.873909,0.9025,207.575,0.128981,3,5.470000,0.168721,...,126.965437,0.000000,0.000000,0.000000,0.000000,-3.640634,0.000000,-3.640634,-2.985102,0.875
2,0.875,0.873609,0.873309,0.873909,0.9500,218.500,0.135770,3,5.626667,0.161314,...,184.934223,0.000000,0.000000,0.000000,0.000000,-0.880799,0.000000,-0.880799,14.901722,0.875
3,0.875,0.873609,0.873309,0.873909,1.0000,230.000,0.142915,3,5.676667,0.254864,...,169.304459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.875
4,0.875,0.873609,0.873309,0.873909,1.0500,241.500,0.150061,3,5.780000,0.131403,...,156.552441,0.000000,0.000000,0.000000,0.000000,1.820317,0.000000,1.820317,9.123869,0.875
5,0.875,0.873609,0.873309,0.873909,1.1025,253.575,0.157564,3,5.913333,0.122565,...,279.457013,0.000000,0.000000,0.000000,0.000000,4.169113,0.000000,4.169113,17.896236,0.875
6,0.875,0.873609,0.873309,0.873909,1.2000,276.000,0.171498,3,5.820000,0.101980,...,256.916329,0.000000,0.000000,0.000000,0.000000,2.524956,0.000000,2.524956,54.190675,0.875
7,0.450,0.448609,0.448309,0.448909,0.8000,184.000,0.114332,3,5.740000,0.160624,...,180.694955,0.000000,0.000000,0.000000,0.000000,1.953819,0.000000,1.953819,4.790875,0.450
8,0.450,0.448609,0.448309,0.448909,0.9025,207.575,0.128981,3,5.786667,0.020548,...,232.926789,0.000000,0.000000,0.000000,0.000000,2.782712,0.000000,2.782712,0.435395,0.450
9,0.450,0.448609,0.448309,0.448909,0.9500,218.500,0.135770,3,5.450000,0.347083,...,280.725647,0.000000,0.000000,0.000000,0.000000,-3.197158,0.000000,-3.197158,5.802952,0.450
10,0.450,0.448609,0.448309,0.448909,1.0000,230.000,0.142915,3,5.630000,0.090921,...,132.751229,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450
11,0.450,0.448609,0.448309,0.448909,1.0500,241.500,0.150061,3,5.630000,0.151217,...,170.513603,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.405275,0.450
12,0.450,0.448609,0.448309,0.448909,1.1025,253.575,0.157564,3,5.666667,0.298478,...,207.454948,0.000000,0.000000,0.000000,0.000000,0.651273,0.000000,0.651273,7.293101,0.450
13,0.450,0.448609,0.448309,0.448909,1.2000,276.000,0.171498,3,5.573333,0.084984,...,43.606829,0.000000,0.000000,0.000000,0.000000,-1.006513,0.000000,-1.006513,11.544812,0.450
14,0.150,0.148609,0.148309,0.148909,0.8000,184.000,0.114332,3,1.113333,0.174420,...,1895.275764,69.000000,7.483315,21704.333333,1855.580652,-1.474926,1.980198,-0.184843,10.953632,0.150
15,0.150,0.148609,0.148309,0.148909,0.9025,207.575,0.128981,3,1.083333,0.097411,...,2016.366204,67.333333,7.845735,21877.000000,1690.174744,-4.129794,-0.495050,-2.772643,16.490256,0.150
16,0.150,0.148609,0.148309,0.148909,0.9500,218.500,0.135770,3,0.990000,0.214165,...,1655.478984,68.000000,7.483315,21619.000000,2295.585474,-12.389381,0.990099,-7.393715,16.748224,0.150
17,0.150,0.148609,0.148309,0.148909,1.0000,230.000,0.142915,3,1.130000,0.189912,...,1676.048196,67.666667,6.599663,21115.666667,2207.095427,0.000000,0.000000,0.000000,0.000000,0.150
18,0.150,0.148609,0.148309,0.148909,1.0500,241.500,0.150061,3,1.013333,0.103387,...,1483.369213,68.000000,8.041559,21694.333333,2282.710426,-10.324484,-0.495050,-6.654344,15.305230,0.150
19,0.150,0.148609,0.148309,0.148909,1.1025,253.575,0.157564,3,1.096667,0.069442,...,1460.571197,67.333333,8.178563,21751.333333,2303.804727,-2.949853,-0.495050,-2.033272,17.792232,0.150
20,0.150,0.148609,0.148309,0.148909,1.2000,276.000,0.171498,3,0.990000,0.162686,...,1311.971629,68.666667,7.408704,21576.333333,2226.397589,-12.389381,1.485149,-7.208872,10.768495,0.150